from __future__ import annotations

from epigraph_ph.adapters.structured_sources import get_structured_source_adapters
from epigraph_ph.core.disease_plugin import DiseasePlugin, LiteratureSiloDefinition, register_disease_plugin


HIV_QUERY_BANKS = {
    "default_hiv": [
        "HIV Philippines care cascade",
        "HIV stigma Philippines",
        "HIV logistics treatment access",
        "HIV CD4 progression",
    ],
    "hiv_direct": [
        "HIV incidence Philippines",
        "AIDS treatment adherence Philippines",
        "HIV key populations MSM TGW PWID",
        "HIV stigma testing uptake",
        "HIV CD4 viral load progression",
        "HIV ART retention and suppression",
    ],
    "upstream_structural": [
        "poverty health access transport affordability",
        "migration mobility commuting health behavior",
        "stigma discrimination health seeking behavior",
        "collective behavior social norms condom use",
        "supply chain diagnostics cold chain clinic access",
        "population dynamics urbanization inequality",
        "telehealth rural access health systems",
        "household out of pocket catastrophic expenditure",
        "drug resistance immune response antiviral compounds",
        "statistical physics collective behavior epidemics",
        "network contagion mobility mixing",
        "geography remoteness health systems",
        "socioeconomic inequality access to care",
    ],
    "philippines_context": [
        "Philippines poverty transport access",
        "Philippines migration urbanization inequality",
        "Philippines culture stigma health seeking",
        "Philippines population dynamics demography",
    ],
    "philippines_subnational": [
        "Metro Manila HIV testing ART suppression",
        "Cebu HIV care cascade treatment access",
        "Davao HIV diagnosis ART retention",
        "CALABARZON HIV mobility stigma access",
        "Central Luzon HIV treatment logistics",
        "Western Visayas HIV clinic access",
        "BARMM HIV transport fragility access",
        "Eastern Visayas HIV disruption typhoon access",
    ],
    "modeling": [
        "epidemic modeling mobility networks",
        "statistical physics contagion social behavior",
        "population dynamics health systems modeling",
    ],
    "biology": [
        "immune response antiviral compounds",
        "CD4 viral reservoir progression",
        "drug resistance long acting therapeutics",
    ],
    "mixed": [
        "Philippines health indicators",
        "Philippines geospatial demographics",
        "health nutrition population statistics",
        "HIV Philippines economics stigma logistics",
        "population dynamics transport access health",
        "HIV biology economics logistics policy",
        "migration behavior disease dynamics",
    ],
}

HIV_DETERMINANT_SILOS = {
    "sexual_risk": LiteratureSiloDefinition("sexual_risk", "Sexual Risk", "Networked sexual risk behavior, concurrency, and condom-use barriers relevant to HIV acquisition and delayed diagnosis.", ["sexual risk behavior network concurrency prevention barriers", "collective sexual risk norms condom use partner concurrency"], "supporting_context"),
    "prevention_access": LiteratureSiloDefinition("prevention_access", "Prevention Access", "Access to condoms, PrEP, outreach, and safe-sex commodities including affordability and last-mile delivery constraints.", ["prevention access prep condoms affordability last mile delivery", "barriers to prevention access safe sex commodities clinic reach"], "supporting_context"),
    "testing_uptake": LiteratureSiloDefinition("testing_uptake", "Testing Uptake", "Testing demand, delayed diagnosis, fear of disclosure, stigma, and community testing reach.", ["testing uptake delayed diagnosis stigma fear disclosure", "barriers to hiv testing uptake outreach demand generation"], "main_predictive_candidate"),
    "linkage_to_care": LiteratureSiloDefinition("linkage_to_care", "Linkage to Care", "Referral completion, treatment initiation delay, service navigation, and diagnosis-to-ART conversion friction.", ["linkage to care referral completion treatment initiation delay", "post diagnosis linkage treatment start service navigation"], "main_predictive_candidate"),
    "retention_adherence": LiteratureSiloDefinition("retention_adherence", "Retention and Adherence", "Retention in care, interruption risk, loss to follow-up, adherence support, and continuity stress.", ["retention in care adherence interruption loss to follow up", "drivers of treatment discontinuity continuity of care stress"], "main_predictive_candidate"),
    "suppression_outcomes": LiteratureSiloDefinition("suppression_outcomes", "Suppression Outcomes", "Viral-load testing, turnaround, documented suppression, and suppression failure barriers.", ["viral suppression outcomes monitoring turnaround documented suppression", "adherence viral load testing and suppression barriers"], "main_predictive_candidate"),
    "mobility_network_mixing": LiteratureSiloDefinition("mobility_network_mixing", "Mobility and Network Mixing", "Commuting, migration, route corridors, sexual-network mixing, and mobility-driven continuity of care stress.", ["mobility network mixing commuting migration sexual networks", "transport corridors mobility mixing care continuity migration"], "supporting_context"),
    "health_system_reach": LiteratureSiloDefinition("health_system_reach", "Health-System Reach", "Facility reach, workforce reach, telehealth, and last-mile service delivery access.", ["health system reach service delivery clinic coverage telehealth", "last mile health system access facility reach workforce shortage"], "supporting_context"),
    "poverty": LiteratureSiloDefinition("poverty", "Poverty", "Household deprivation, catastrophic cost, and poverty-driven access barriers.", ["poverty deprivation healthcare affordability treatment continuity", "household poverty burden and delayed healthcare seeking"], "supporting_context"),
    "transport_friction": LiteratureSiloDefinition("transport_friction", "Transport Friction", "Travel burden, ferry disruption, clinic travel cost, and transport-mediated access friction.", ["transport friction travel burden ferry disruption healthcare access", "travel time congestion remoteness treatment access logistics"], "supporting_context"),
    "cash_instability": LiteratureSiloDefinition("cash_instability", "Cash Instability", "Income shocks, liquidity instability, remittance cycles, and short-run affordability volatility.", ["cash instability income shocks household liquidity care interruption", "financial volatility informal work income instability treatment adherence"], "supporting_context"),
    "labor_migration": LiteratureSiloDefinition("labor_migration", "Labor Migration", "Internal migration, mobile labor, remittance-linked movement, and treatment discontinuity risk among mobile populations.", ["labor migration internal migration remittance cycles healthcare continuity", "mobile labor populations migration and clinic disengagement"], "supporting_context"),
    "remoteness": LiteratureSiloDefinition("remoteness", "Remoteness", "Archipelagic remoteness, island and peripheral access constraints, and diagnostic isolation.", ["remoteness archipelago service access peripheral province health reach", "remote communities treatment access diagnostic access islands"], "supporting_context"),
    "congestion_travel_time": LiteratureSiloDefinition("congestion_travel_time", "Congestion and Travel Time", "Traffic, commute burden, travel delays, and appointment failure risk from transport congestion.", ["urban congestion travel time clinic access missed appointments", "commute burden traffic delay treatment continuity health access"], "supporting_context"),
    "social_capital": LiteratureSiloDefinition("social_capital", "Social Capital", "Trust, collective efficacy, community support, and disclosure or support environments shaping care engagement.", ["social capital trust community support healthcare engagement", "collective efficacy social capital and testing linkage behavior"], "supporting_context"),
    "housing_precarity": LiteratureSiloDefinition("housing_precarity", "Housing Precarity", "Unstable housing, shelter insecurity, eviction stress, and address instability affecting continuity of care.", ["housing precarity unstable housing treatment continuity health access", "shelter insecurity and healthcare retention adherence"], "supporting_context"),
    "education": LiteratureSiloDefinition("education", "Education", "Educational attainment, health literacy, and schooling-linked risk, prevention, and testing behavior.", ["education attainment health literacy testing uptake prevention access", "schooling education and sexual health risk behavior"], "supporting_context"),
    "collective_risk_behavior": LiteratureSiloDefinition("collective_risk_behavior", "Collective Risk Behavior", "Peer effects, group norms, sexual-network clustering, and collective behavior around exposure or care seeking.", ["collective risk behavior group norms sexual networks", "peer effects collective behavior and health seeking risk"], "supporting_context"),
    "policy_implementation_weakness": LiteratureSiloDefinition("policy_implementation_weakness", "Policy Implementation Weakness", "Last-mile execution failure, governance bottlenecks, rollout weakness, and implementation gaps.", ["policy implementation weakness governance bottlenecks service delivery failure", "implementation gap last mile policy execution health systems"], "supporting_context"),
}


HIV_NODE_GRAPH_DEFAULTS = [
    {"block_id": "mobility_network_mixing", "node_type": "advisory", "core_distance": 2, "acts_on": "both", "positive_support_allowed": True, "enabled": True},
    {"block_id": "logistics_access", "node_type": "constraint", "core_distance": 2, "acts_on": "both", "positive_support_allowed": False, "enabled": True},
    {"block_id": "service_delivery_infrastructure", "node_type": "constraint", "core_distance": 2, "acts_on": "both", "positive_support_allowed": False, "enabled": True},
    {"block_id": "stigma_behavior_information", "node_type": "advisory", "core_distance": 2, "acts_on": "both", "positive_support_allowed": True, "enabled": True},
    {"block_id": "population_structure_demography", "node_type": "decision_modifier", "core_distance": 3, "acts_on": "both", "positive_support_allowed": True, "enabled": True},
    {"block_id": "policy_implementation", "node_type": "constraint", "core_distance": 2, "acts_on": "decision_layer", "positive_support_allowed": False, "enabled": True},
    {"block_id": "benchmark_guardrails", "node_type": "constraint", "core_distance": 1, "acts_on": "both", "positive_support_allowed": False, "enabled": True},
]


HIV_PROVINCE_ARCHETYPE_DEFINITIONS = {
    "urban_high_throughput": {
        "display_name": "Urban High Throughput",
        "description": "Dense, high-volume provinces with strong access, strong diagnosis reach, and comparatively efficient ART/VL throughput.",
        "prototype_features": {
            "urbanity": 0.90,
            "accessibility": 0.86,
            "awareness": 0.72,
            "stress": 0.34,
            "kp_focus": 0.68,
            "evidence_strength": 0.82,
            "diagnosed_share": 0.74,
            "art_share": 0.48,
            "suppression_share": 0.34,
            "testing_share": 0.26,
        },
        "reporting_noise": 0.16,
        "diagnosis_prior_shift": 0.26,
        "linkage_prior_shift": 0.14,
        "retention_prior_shift": 0.08,
        "vl_testing_prior_shift": 0.18,
        "documentation_prior_shift": 0.12,
        "notes": ["Fits metro treatment hubs and dense corridor provinces."],
    },
    "migrant_corridor": {
        "display_name": "Migrant Corridor",
        "description": "Mobility-heavy provinces with active diagnosis but weaker continuity because labor movement and corridor churn disrupt care.",
        "prototype_features": {
            "urbanity": 0.72,
            "accessibility": 0.67,
            "awareness": 0.56,
            "stress": 0.60,
            "kp_focus": 0.73,
            "evidence_strength": 0.56,
            "diagnosed_share": 0.67,
            "art_share": 0.39,
            "suppression_share": 0.24,
            "testing_share": 0.20,
        },
        "reporting_noise": 0.28,
        "diagnosis_prior_shift": 0.12,
        "linkage_prior_shift": 0.02,
        "retention_prior_shift": -0.12,
        "vl_testing_prior_shift": -0.02,
        "documentation_prior_shift": -0.04,
        "notes": ["Care interruption risk is higher than diagnosis failure risk."],
    },
    "remote_island": {
        "display_name": "Remote Island",
        "description": "Peripheral or island provinces where travel burden, sparse facilities, and low monitoring reach dominate the cascade bottleneck.",
        "prototype_features": {
            "urbanity": 0.18,
            "accessibility": 0.22,
            "awareness": 0.34,
            "stress": 0.64,
            "kp_focus": 0.28,
            "evidence_strength": 0.33,
            "diagnosed_share": 0.52,
            "art_share": 0.29,
            "suppression_share": 0.18,
            "testing_share": 0.11,
        },
        "reporting_noise": 0.36,
        "diagnosis_prior_shift": -0.10,
        "linkage_prior_shift": -0.12,
        "retention_prior_shift": -0.08,
        "vl_testing_prior_shift": -0.16,
        "documentation_prior_shift": -0.10,
        "notes": ["Transport friction and remoteness dominate the bottleneck."],
    },
    "fragile_service_network": {
        "display_name": "Fragile Service Network",
        "description": "Provinces with visible care access but brittle hub/lab/supply performance, leading to treatment and monitoring instability.",
        "prototype_features": {
            "urbanity": 0.46,
            "accessibility": 0.44,
            "awareness": 0.50,
            "stress": 0.86,
            "kp_focus": 0.46,
            "evidence_strength": 0.46,
            "diagnosed_share": 0.64,
            "art_share": 0.33,
            "suppression_share": 0.19,
            "testing_share": 0.13,
        },
        "reporting_noise": 0.34,
        "diagnosis_prior_shift": 0.02,
        "linkage_prior_shift": -0.18,
        "retention_prior_shift": -0.24,
        "vl_testing_prior_shift": -0.20,
        "documentation_prior_shift": -0.16,
        "notes": ["The main problem is weak conversion and monitoring, not pure case finding."],
    },
    "under_reporting_province": {
        "display_name": "Under-reporting Province",
        "description": "Observed cascade shares are artificially depressed because reporting/documentation is weak relative to expected access and burden.",
        "prototype_features": {
            "urbanity": 0.54,
            "accessibility": 0.52,
            "awareness": 0.44,
            "stress": 0.50,
            "kp_focus": 0.52,
            "evidence_strength": 0.16,
            "diagnosed_share": 0.45,
            "art_share": 0.27,
            "suppression_share": 0.15,
            "testing_share": 0.10,
        },
        "reporting_noise": 0.58,
        "diagnosis_prior_shift": 0.04,
        "linkage_prior_shift": -0.05,
        "retention_prior_shift": -0.04,
        "vl_testing_prior_shift": -0.10,
        "documentation_prior_shift": -0.14,
        "notes": ["High noise and weak documentation should reduce observation trust more than latent burden."],
    },
}


HIV_PRIOR_HYPERPARAMETERS = {
    "phase3": {
        "observation_class_weight": {
            "direct_observed": 1.0,
            "bounded_observed": 0.75,
            "proxy_observed": 0.35,
            "prior_only": 0.12,
        },
        "kp_prior": [0.62, 0.18, 0.03, 0.05, 0.03, 0.03, 0.06],
        "age_prior": [0.26, 0.36, 0.24, 0.14],
        "sex_prior": [0.78, 0.22],
        "cd4_prior": [0.22, 0.28, 0.25, 0.25],
        "transition_prior": [0.10, 0.13, 0.11, 0.05, 0.08],
        "duration_template": [
            [0.38, 0.24, 0.20, 0.18],
            [0.55, 0.23, 0.13, 0.09],
            [0.30, 0.24, 0.23, 0.23],
            [0.12, 0.16, 0.24, 0.48],
            [0.28, 0.24, 0.22, 0.26],
        ],
        "age_progress_rates": [1.0 / 120.0, 1.0 / 120.0, 1.0 / 180.0, 0.0],
        "subgroup_counter_strength": {
            "national": {"kp": 18.0, "age": 16.0, "sex": 16.0},
            "region": 11.0,
            "province": 7.5,
        },
        "subgroup_network_adjustment": {
            "kp": {
                "msm": {"urbanity": 0.10, "awareness": 0.06},
                "tgw": {"urbanity": 0.03},
                "pwid": {"stress": 0.07},
                "remaining_population": {"urbanity": -0.06},
            },
            "age": {
                "15_24": {"urbanity": 0.05},
                "25_34": {"awareness": 0.03},
                "50_plus": {"urbanity": -0.04},
            },
            "sex": {
                "male": {"urbanity": 0.07, "urbanity_center": 0.45, "stress": 0.05},
                "female": {"urbanity": -0.03, "urbanity_center": 0.55},
            },
        },
        "observation_bounds": {
            "diagnosed_stock": [0.04, 0.98],
            "art_stock": [0.01, 0.96],
            "documented_suppression": [0.0, 0.94],
            "testing_coverage": [0.0, 0.96],
            "deaths": [0.0, 0.12],
        },
        "observation_fallback": {
            "diagnosed_floor": 0.08,
            "art_floor": 0.02,
            "suppression_floor": 0.01,
            "testing_floor": 0.01,
            "second95_prior": 0.66,
            "tested_among_art_prior": 0.42,
            "suppressed_among_art_prior": 0.58,
        },
        "state_initialization": {
            "loss_share_lower": 0.05,
            "loss_share_upper": 0.85,
            "loss_share_art_gap_weight": 0.25,
            "loss_share_suppression_gap_weight": 0.15,
            "prior_strength_lower": 6.0,
            "prior_strength_upper": 26.0,
        },
        "latent_observation": {
            "support_floor": 0.05,
            "support_power": 0.85,
            "province_offset_sigma": 0.28,
            "month_offset_sigma": 0.22,
            "anchor_reversion_scale": 9.0,
            "offset_regularization": 0.05,
        },
        "subgroup_hyperpriors": {
            "feature_coef_sigma": 0.18,
            "state_effect_sigma": 0.10,
            "transition_effect_sigma": 0.08,
        },
        "cd4_overlay": {
            "low_art_weight": 0.10,
            "low_suppression_weight": 0.08,
            "mid_low_weight": 0.50,
            "high_suppression_weight": 0.12,
        },
        "cd4_hyperpriors": {
            "age_low_sigma": 0.08,
            "kp_sex_high_sigma": 0.06,
            "transition_coef_sigma": 0.10,
        },
        "archetype_hyperpriors": {
            "transition_scale_sigma": 0.25,
            "process_scale_sigma": 0.22,
            "observation_scale_sigma": 0.18,
        },
        "torch_map_loss_scales": {
            "optimizer_lr": 0.045,
            "diagnosed_penalty_scale": 4.0,
            "official_reference_penalty_scale": 18.0,
            "national_anchor_penalty_scale": 12.0,
            "harp_program_penalty_scale": 24.0,
            "linkage_penalty_scale": 22.0,
            "suppression_penalty_scale": 0.0,
            "lower_bound_penalty": 5.0,
            "hierarchy_penalty": 2.0,
            "stock_penalty": 8.0,
            "duration_smooth_multiplier": 0.25,
            "fit_steps": 160,
            "regularization": {
                "region_transition": 0.15,
                "province_transition_prior": 0.16,
                "province_process_prior": 0.08,
                "plausibility": 0.05,
            },
        },
        "jax_svi_priors": {
            "transition_prior_sigma": 0.35,
            "province_transition_sigma": 0.12,
            "vl_test_sigma": 0.20,
            "suppressed_given_test_sigma": 0.16,
            "vl_province_sigma": 0.18,
            "documentation_province_sigma": 0.16,
        },
        "frozen_backtest": {
            "default_initial_state": [0.48, 0.19, 0.18, 0.10, 0.05],
            "empirical_transition_targets": {
                "positive_mass_weight": [0.55, 0.40, 0.45, 0.00, 0.28],
                "negative_mass_weight": [-0.10, 0.00, -0.12, 0.32, -0.04],
                "feature_mean_weight": [0.00, 0.10, 0.00, 0.00, 0.00],
                "feature_std_weight": [0.00, 0.00, 0.00, 0.08, 0.00],
                "intercept": [-0.25, -0.55, -0.70, -1.55, -1.05],
                "clip_floor": 0.01,
                "clip_ceiling": 0.92,
            },
            "semi_markov_hyperpriors": {
                "base_rate_floor": 0.05,
                "base_rate_ceiling": 0.95,
                "national_logit_sigma": 0.45,
                "sigma_region": 0.25,
                "sigma_province": 0.20,
                "sigma_feature": 0.15,
                "sigma_intervention": 0.12,
                "horseshoe_global_scale": 0.35,
                "horseshoe_local_scale": 1.0,
                "duration_prior_mean": [0.08, 0.07, 0.10, 0.06, 0.07],
                "duration_prior_sigma": 0.05,
                "beta_concentration": 24.0,
                "beta_floor": 0.1,
            },
            "posterior_inference": {
                "inference_method": "svi",
                "svi_steps": 150,
                "posterior_samples": 64,
                "optimizer_lr": 0.03,
                "seed": 17,
                "nuts_warmup": 96,
                "nuts_samples": 128,
                "nuts_chains": 2,
                "nuts_target_accept_prob": 0.85,
                "nuts_max_tree_depth": 8,
                "calibration_interval": [0.05, 0.95],
                "categorical_particle_count": 256,
            },
            "fallback_posterior": {
                "posterior_samples": 48,
                "mean_floor": 0.05,
                "mean_ceiling": 0.95,
                "transition_noise_scale": 0.03,
                "national_logit_scale": 0.08,
                "region_offset_scale": 0.06,
                "province_offset_scale": 0.08,
                "feature_weight_scale": 0.05,
                "duration_mean": [0.08, 0.07, 0.10, 0.06, 0.07],
                "duration_scale": 0.02,
            },
            "evolution": {
                "duration_effect_scale": 6.0,
                "transition_floor": 0.001,
                "transition_ceiling": 0.95,
                "state_mass_eps": 1e-6,
                "duration_floor": 0.0,
                "duration_ceiling": 36.0,
            },
            "baseline_family": {
                "arima_order": [1, 0, 0],
                "arima_phi_clip": 0.98,
                "compartment_floor": 1e-5,
                "spatial_holdout_months": 6,
            },
            "legacy_selection": {
                "top_k_per_block": 20,
                "mass_error_tolerance": 1e-4,
            },
            "tuning": {
                "initial_candidates": [
                    {
                        "label": "base_short",
                        "u_to_d_prior": 0.10,
                        "d_to_a_prior": 0.13,
                        "diagnosed_penalty_scale": 4.0,
                        "harp_program_penalty_scale": 24.0,
                        "linkage_penalty_scale": 22.0,
                        "national_anchor_penalty_scale": 12.0,
                        "fit_steps": 90,
                    },
                    {
                        "label": "base_short_supp_soft",
                        "u_to_d_prior": 0.10,
                        "d_to_a_prior": 0.13,
                        "diagnosed_penalty_scale": 4.0,
                        "harp_program_penalty_scale": 24.0,
                        "linkage_penalty_scale": 22.0,
                        "national_anchor_penalty_scale": 12.0,
                        "suppression_penalty_scale": 4.0,
                        "fit_steps": 90,
                    },
                    {
                        "label": "dx_low_link_mid",
                        "u_to_d_prior": 0.06,
                        "d_to_a_prior": 0.14,
                        "diagnosed_penalty_scale": 10.0,
                        "harp_program_penalty_scale": 28.0,
                        "linkage_penalty_scale": 24.0,
                        "national_anchor_penalty_scale": 14.0,
                        "fit_steps": 90,
                    },
                    {
                        "label": "dx_low_link_mid_supp_mid",
                        "u_to_d_prior": 0.06,
                        "d_to_a_prior": 0.14,
                        "diagnosed_penalty_scale": 10.0,
                        "harp_program_penalty_scale": 28.0,
                        "linkage_penalty_scale": 24.0,
                        "national_anchor_penalty_scale": 14.0,
                        "suppression_penalty_scale": 6.0,
                        "fit_steps": 90,
                    },
                    {
                        "label": "dx_very_low_link_mid",
                        "u_to_d_prior": 0.04,
                        "d_to_a_prior": 0.14,
                        "diagnosed_penalty_scale": 14.0,
                        "harp_program_penalty_scale": 32.0,
                        "linkage_penalty_scale": 26.0,
                        "national_anchor_penalty_scale": 14.0,
                        "fit_steps": 90,
                    },
                    {
                        "label": "dx_very_low_link_high",
                        "u_to_d_prior": 0.04,
                        "d_to_a_prior": 0.18,
                        "diagnosed_penalty_scale": 14.0,
                        "harp_program_penalty_scale": 34.0,
                        "linkage_penalty_scale": 30.0,
                        "national_anchor_penalty_scale": 14.0,
                        "fit_steps": 90,
                    },
                    {
                        "label": "dx_ultra_low_link_high",
                        "u_to_d_prior": 0.02,
                        "d_to_a_prior": 0.18,
                        "diagnosed_penalty_scale": 18.0,
                        "harp_program_penalty_scale": 40.0,
                        "linkage_penalty_scale": 32.0,
                        "national_anchor_penalty_scale": 16.0,
                        "fit_steps": 90,
                    },
                    {
                        "label": "dx_low_link_soft",
                        "u_to_d_prior": 0.05,
                        "d_to_a_prior": 0.12,
                        "diagnosed_penalty_scale": 12.0,
                        "harp_program_penalty_scale": 30.0,
                        "linkage_penalty_scale": 22.0,
                        "national_anchor_penalty_scale": 14.0,
                        "fit_steps": 90,
                    },
                    {
                        "label": "dx_ultra_low_link_mid",
                        "u_to_d_prior": 0.02,
                        "d_to_a_prior": 0.14,
                        "diagnosed_penalty_scale": 20.0,
                        "harp_program_penalty_scale": 42.0,
                        "linkage_penalty_scale": 28.0,
                        "national_anchor_penalty_scale": 18.0,
                        "fit_steps": 90,
                    },
                    {
                        "label": "dx_ultra_low_link_mid_supp_high",
                        "u_to_d_prior": 0.02,
                        "d_to_a_prior": 0.14,
                        "diagnosed_penalty_scale": 20.0,
                        "harp_program_penalty_scale": 42.0,
                        "linkage_penalty_scale": 28.0,
                        "national_anchor_penalty_scale": 18.0,
                        "suppression_penalty_scale": 10.0,
                        "fit_steps": 90,
                    },
                ],
                "adaptive_rules": {
                    "u_to_d_floor_soft": 0.0025,
                    "u_to_d_floor_hard": 0.001,
                    "u_to_d_floor_balanced": 0.005,
                    "u_to_d_scale_soft": 0.50,
                    "u_to_d_scale_hard": 0.35,
                    "d_to_a_ceiling_soft": 0.24,
                    "d_to_a_ceiling_hard": 0.28,
                    "d_to_a_ceiling_supp": 0.26,
                    "d_to_a_ceiling_balanced": 0.22,
                    "d_to_a_increment_soft": 0.04,
                    "d_to_a_increment_hard": 0.08,
                    "d_to_a_increment_supp": 0.06,
                    "d_to_a_increment_balanced": 0.02,
                    "diagnosed_penalty_soft": 8.0,
                    "diagnosed_penalty_hard": 12.0,
                    "diagnosed_penalty_balanced": 10.0,
                    "official_penalty_floor_soft": 8.0,
                    "official_penalty_floor_hard": 6.0,
                    "official_penalty_reduction_soft": 8.0,
                    "official_penalty_reduction_hard": 10.0,
                    "official_penalty_reduction_balanced": 6.0,
                    "national_penalty_floor_soft": 6.0,
                    "national_penalty_floor_hard": 4.0,
                    "national_penalty_reduction_soft": 8.0,
                    "national_penalty_reduction_hard": 10.0,
                    "national_penalty_reduction_balanced": 6.0,
                    "harp_penalty_add_soft": 10.0,
                    "harp_penalty_add_hard": 14.0,
                    "harp_penalty_add_supp": 12.0,
                    "harp_penalty_add_balanced": 12.0,
                    "linkage_penalty_add_soft": 8.0,
                    "linkage_penalty_add_hard": 12.0,
                    "linkage_penalty_add_supp": 10.0,
                    "linkage_penalty_add_balanced": 10.0,
                    "suppression_penalty_floor_soft": 4.0,
                    "suppression_penalty_floor_hard": 6.0,
                    "suppression_penalty_floor_balanced": 5.0,
                    "suppression_penalty_increment_soft": 3.0,
                    "suppression_penalty_increment_hard": 5.0,
                    "suppression_penalty_increment_balanced": 4.0,
                    "suppression_penalty_trial": 6.0,
                    "suppression_penalty_trial_hard": 10.0,
                    "suppression_penalty_trial_balanced": 8.0,
                    "adaptive_fit_steps": 100,
                    "final_fit_steps": 160,
                    "max_adaptive_rounds": 3,
                },
            },
        },
    },
    "province_archetypes": {
        "softmax_temperature": 0.35,
        "softmax_min_temperature": 1e-3,
        "default_feature_value": 0.5,
        "zero_variance_midpoint": 0.5,
        "min_denominator": 1e-6,
        "reporting_noise_floor": 0.05,
        "reporting_noise_ceiling": 0.85,
        "definitions": HIV_PROVINCE_ARCHETYPE_DEFINITIONS,
        "feature_weights": {
            "urbanity": 0.85,
            "accessibility": 0.95,
            "awareness": 0.75,
            "stress": 0.95,
            "kp_focus": 0.60,
            "evidence_strength": 0.85,
            "diagnosed_share": 0.75,
            "art_share": 0.70,
            "suppression_share": 0.65,
            "testing_share": 0.70,
            "under_reporting_cue": 1.10,
        },
        "under_reporting_bonus": {
            "default": 0.15,
            "fragile_service_network": 0.25,
            "under_reporting_province": 0.95,
        },
        "migrant_corridor_bonus": {"urbanity": 0.20, "stress": 0.30},
        "sparse_pretraining_weight": {"base": 0.20, "scale": 0.80, "floor": 0.20, "ceiling": 0.95},
        "transition_shift_mix": {
            "a_to_v_retention_weight": 0.20,
            "a_to_v_documentation_weight": 0.10,
            "a_to_l_retention_weight": -0.65,
            "a_to_l_noise_weight": 0.08,
            "l_to_a_retention_weight": 0.75,
        },
        "observation_weight_mix": {
            "reporting_noise_weight": 0.55,
            "evidence_base": 0.60,
            "evidence_scale": 0.40,
            "floor": 0.35,
            "ceiling": 1.0,
        },
        "under_reporting_cue_mix": {
            "accessibility": 0.55,
            "urbanity": 0.20,
            "diagnosed_share": -0.45,
            "testing_share": -0.30,
            "evidence_gap": 0.25,
        },
        "synthetic_generator": {
            "logistic_scale": 6.0,
            "logistic_center": 0.45,
            "diagnosed_base": 0.72,
            "diagnosed_scale": 0.28,
            "diagnosed_floor": 0.02,
            "diagnosed_ceiling": 0.97,
            "art_base": 0.65,
            "art_scale": 0.35,
            "art_floor": 0.01,
            "suppression_base": 0.55,
            "suppression_scale": 0.45,
            "suppression_floor": 0.005,
            "testing_base": 0.60,
            "testing_scale": 0.40,
            "testing_floor": 0.005,
            "death_base": 0.04,
            "death_reporting_scale": 0.05,
            "death_time_scale": 0.02,
            "death_floor": 0.01,
            "death_ceiling": 0.18,
        },
    },
}


HIV_REFERENCE_DATA = {
    "phase3": {
        "official_reference_points": [
            {
                "label": "UNAIDS Philippines Executive Summary (Most recent data as of 2022)",
                "month": "2022-01",
                "reference": {"first95": 0.63, "second95": 0.66, "overall_suppressed": 0.407},
                "source_url": "https://sustainability.unaids.org/wp-content/uploads/2024/06/Philippines-Executive-Summary-May-2024.pdf",
            },
            {
                "label": "WHO/UNAIDS Philippines joint release (March 2025 operational snapshot, published June 11 2025)",
                "month": "2025-01",
                "reference": {"first95": 0.55, "second95": 0.66, "documented_suppression_among_art": 0.40},
                "source_url": "https://www.who.int/philippines/news/detail/11-06-2025-unaids--who-support-doh-s-call-for-urgent-action-as-the-philippines-faces-the-fastest-growing-hiv-surge-in-the-asia-pacific-region",
            },
        ],
        "harp_program_points": [
            {
                "label": "Philippine HIV Care Cascade as of December 2024",
                "month": "2025-01",
                "estimated_plhiv": 216900.0,
                "diagnosed": 135026.0,
                "on_art": 90854.0,
                "viral_load_tested": 43534.0,
                "suppressed": 41164.0,
                "source_label": "2025 PH HIV Estimates Core Team for WHO, page 13",
            }
        ],
    }
}


HIV_NUMERICAL_STABILIZERS = {
    "phase1": {
        "min_denominator": 1e-6,
        "iqr_eps": 1e-6,
        "winsor_eps": 1e-6,
        "boxcox_eps": 1e-6,
        "huber_eps": 1e-6,
    },
    "phase2": {
        "corr_eps": 1e-6,
        "mi_eps": 1e-6,
        "fisher_clip": 0.999999,
        "condition_eps": 1e-6,
    },
    "phase3": {
        "probability_eps": 1e-5,
        "mass_eps": 1e-6,
        "clip_floor": 1e-4,
        "neutral_probability": 0.5,
    },
    "phase4": {
        "allocation_eps": 1e-8,
        "state_mass_eps": 1e-6,
    },
}


HIV_CONSTRAINT_SETTINGS = {
    "phase0": {
        "source_budget_weights": {
            "pubmed": 1.0,
            "crossref": 1.4,
            "openalex": 2.2,
            "semanticscholar": 1.2,
            "arxiv": 0.8,
            "biorxiv": 0.8,
            "kaggle": 0.3,
        },
        "mode_max_queries": {"default": 6, "broad": 32, "massive": 96, "ultra": 192, "megacrawl": 384},
        "large_corpus": {
            "variant_modes": ["massive", "ultra", "megacrawl"],
            "query_variant_templates": [
                "{query} systematic review",
                "{query} implementation barriers",
                "{query} cohort OR cross-sectional",
                "{query} Philippines OR Southeast Asia",
            ],
            "min_literature_year": 2010,
            "metadata_only_default": True,
            "abstract_char_limit": 2400,
            "shard_count_default": 12,
            "shard_merge_chunk_size": 5000,
            "page_sizes": {
                "pubmed": 200,
                "crossref": 200,
                "openalex": 200,
                "semanticscholar": 100,
                "arxiv": 100,
            },
            "max_pages_per_query": 10,
        },
        "wide_sweep_scoring": {
            "domain_quality_hiv_hit_weight": 0.18,
            "domain_quality_upstream_hit_weight": 0.08,
            "domain_quality_long_text_bonus": 0.12,
            "long_text_min_chars": 120,
            "philippines_geo_bonus": 0.12,
            "southeast_asia_geo_bonus": 0.05,
            "query_silo_match_bonus": 0.08,
            "soft_hint_bonus": 0.05,
            "precision_penalty_offtopic_biomed": 0.35,
            "precision_penalty_missing_signal": 0.18,
            "precision_penalty_generic_science": 0.22,
            "accepted_upstream_silo_match_floor": 0.34,
            "accepted_upstream_signal_floor": 1,
            "review_upstream_silo_match_floor": 0.18,
            "hiv_direct_per_hit": 0.24,
            "hiv_direct_lane_bonus": 0.18,
            "upstream_per_hit": 0.10,
            "upstream_lane_bonus": 0.16,
            "accepted_hiv_threshold": 0.35,
            "accepted_upstream_threshold": 0.25,
            "review_floor": 0.15,
            "review_fraction_of_min": 0.60,
            "min_domain_quality": 0.20,
        },
        "alignment": {
            "log_transform_value_threshold": 100000.0,
            "missing_rate_per_field": 0.3333,
            "instability_default": 0.05,
            "instability_platform": {"offline_seed": 0.15, "kaggle": 0.15},
            "quality_missing_scale": 1.5,
            "quality_instability_scale": 1.2,
            "temporal_decay": 0.03,
            "semantic_threshold": 0.15,
            "mi_threshold": 0.0,
        },
        "ocr": {
            "pdf_requires_ocr_avg_chars": 120.0,
            "render_dpi": 200.0,
        },
        "chunking": {
            "target_chars": 1200,
            "overlap_chars": 180,
            "min_chunk_chars": 180,
            "max_chunks_per_block": 10,
        },
        "chunk_soft_candidates": {
            "min_chunk_chars": 220,
            "max_chunks_per_document": 12,
            "max_candidates_per_chunk": 8,
            "excerpt_chars": 240,
        },
        "second_pass_canonicalizer": {
            "generic_name": "numeric_observation",
            "context_window_chars": 180,
            "drop_unitless_small_max": 20.0,
            "drop_signal_floor": 2,
            "drop_numeric_only_text_max_chars": 4,
            "query_silo_to_canonical": {
                "sexual_risk": "sexual_risk",
                "prevention_access": "prevention_access",
                "testing_uptake": "testing_uptake",
                "linkage_to_care": "linkage_to_care",
                "retention_adherence": "retention_adherence",
                "suppression_outcomes": "suppression_outcomes",
                "mobility_network_mixing": "mobility_network_mixing",
                "health_system_reach": "health_system_reach",
                "poverty": "poverty_rate",
                "transport_friction": "transport_friction",
                "cash_instability": "cash_instability",
                "labor_migration": "labor_migration",
                "remoteness": "remoteness",
                "congestion_travel_time": "travel_time",
                "social_capital": "social_capital",
                "housing_precarity": "housing_precarity",
                "education": "education_level",
                "collective_risk_behavior": "collective_risk_behavior",
                "policy_implementation_weakness": "policy_implementation_weakness",
            },
            "platform_to_canonical": {
                "google_mobility": "mobility_network_mixing",
                "transport_proxy": "travel_time",
                "world_bank_wdi": "poverty_rate",
                "philhealth": "philhealth_coverage",
                "philgis_psgc": "remoteness",
                "doh_facility_stats": "clinics_per_capita",
                "ndhs": "sexual_risk",
                "yafs": "sexual_risk",
                "fies": "poverty_rate",
            },
        },
        "schema_validation": {
            "generic_canonical_names": ["numeric_observation", "mixed", "modeling", "biology", "hiv_direct", "upstream_structural", "philippines_context", "philippines_subnational"],
            "low_specificity_penalty": 0.25,
            "direct_measurement_threshold": 0.75,
        },
        "review_queue": {
            "low_confidence_threshold": 0.45,
            "generic_candidate_limit": 250,
            "document_review_limit": 250,
        },
        "rights_and_reproducibility": {
            "review_domains": ["doi.org", "pubmed.ncbi.nlm.nih.gov", "openalex.org", "arxiv.org", "semanticscholar.org", "crossref.org"],
            "official_public_platforms": ["who", "unaids", "doh_philippines", "gov_ph", "un", "ndhs", "yafs", "fies", "philgis_psgc", "philhealth", "google_mobility", "world_bank_wdi", "transport_proxy", "doh_facility_stats"],
        },
        "tooling_reality": {
            "design_only_tools": ["docling", "grobid", "camelot", "qwen2_vl", "bge_m3", "llama_3_1_8b", "ray", "gpytorch"],
            "implemented_tools": ["duckdb", "pyarrow_parquet", "faiss", "chromadb", "sentence_transformers", "transformers", "pymupdf", "lighton_ocr_sidecar"],
        },
        "resource_tracking": {
            "stage_names": ["harvest", "score_wide_sweep", "parse", "extract", "index", "literature_review"],
        },
        "confidence": {
            "skip_live_normalizer": 0.55,
            "default_live_normalizer": 0.65,
            "structured_anchor": 0.98,
        },
        "retry_pause_seconds": [0.0, 0.5, 1.0],
        "request_sleep_seconds": 0.1,
    },
    "phase1": {
        "denominator_rules": {
            "default_count_denominator": "population_count",
            "identity_features": [
                "art_uptake_rate",
                "biological_progression_modifier",
                "clinics_per_capita",
                "collective_risk_behavior",
                "congestion_travel_time",
                "economic_access_constraint",
                "education",
                "health_expenditure",
                "health_system_reach",
                "hiv_direct",
                "hiv_knowledge_index",
                "housing_precarity",
                "labor_migration",
                "linkage_to_care",
                "mobility_friction",
                "mobility_network_mixing",
                "philhealth_coverage",
                "plhiv_prevalence",
                "policy_implementation_weakness",
                "poverty",
                "poverty_rate",
                "prevention_access",
                "prevention_coverage",
                "remoteness",
                "retention_adherence",
                "service_delivery_reach",
                "sexual_risk",
                "social_capital",
                "stigma_barrier",
                "suppression_outcomes",
                "testing_rate",
                "testing_uptake",
                "transport_friction",
                "travel_time",
                "treatment_cost",
                "viral_suppression_rate",
            ],
            "canonical_denominators": {
                "case_count": "population_count",
                "cd4_count": "population_count",
                "fsw_population_share": "population_count",
                "hiv_incidence": "population_count",
                "idu_prevalence": "population_count",
                "msm_population_share": "population_count",
                "viral_load": "population_count",
            },
        },
        "winsorization": {
            "lower_quantile": 0.01,
            "upper_quantile": 0.99,
        },
        "preprocessing": {
            "compute_backend": "auto",
            "prefer_gpu": True,
            "transform_mode": "log1p",
            "boxcox_lambda": 0.25,
            "boxcox_shift": 1.0,
            "scaling_mode": "iqr",
            "huber_delta": 1.5,
            "huber_steps": 3,
            "interop_mode": "dlpack",
        },
        "missing_data": {
            "median_impute": True,
            "quality_beta": 1.0,
            "quality_gamma": 1.0,
            "temporal_decay_rho": 0.1,
            "minimum_weight": 0.1,
        },
        "evidence_class_weights": {
            "base": 0.25,
            "observed_numeric": 1.0,
            "numeric_prior": 0.65,
            "hiv_literature_seed": 0.45,
            "upstream_literature_seed": 0.35,
            "anchor_bonus": 0.15,
            "direct_measurement_bonus": 0.10,
            "ceiling": 1.0,
        },
        "reliability_class_rules": {
            "official_routine_anchor": {"tier": 1.0, "measurement": 0.95, "sampling": 0.9, "delay": 0.85, "hint": "promotion_eligible"},
            "official_survey": {"tier": 0.88, "measurement": 0.82, "sampling": 0.74, "delay": 0.8, "hint": "promotion_eligible"},
            "scientific_numeric_study": {"tier": 0.8, "measurement": 0.78, "sampling": 0.72, "delay": 0.72, "hint": "promotion_eligible"},
            "scientific_qualitative_study": {"tier": 0.6, "measurement": 0.55, "sampling": 0.58, "delay": 0.7, "hint": "candidate_only"},
            "structured_repository": {"tier": 0.7, "measurement": 0.6, "sampling": 0.65, "delay": 0.75, "hint": "candidate_only"},
            "proxy_inferred": {"tier": 0.48, "measurement": 0.42, "sampling": 0.5, "delay": 0.68, "hint": "candidate_only"},
            "literature_only_seed": {"tier": 0.32, "measurement": 0.3, "sampling": 0.38, "delay": 0.62, "hint": "candidate_only"},
        },
        "bias_class_thresholds": {
            "measurement_low": 0.8,
            "measurement_moderate": 0.55,
            "sampling_low": 0.8,
            "sampling_moderate": 0.6,
        },
        "spatial_relevance_by_geo": {
            "province": 0.95,
            "city": 0.95,
            "region": 0.9,
            "national": 0.8,
            "global": 0.45,
            "unknown": 0.55,
        },
        "bias_penalty_mix": {
            "measurement": 0.35,
            "sampling": 0.25,
            "temporal_freshness": 0.2,
            "spatial_relevance": 0.2,
        },
        "replication_weight": {
            "base": 0.45,
            "step": 0.15,
            "ceiling": 1.0,
            "bias_penalty_discount": 0.08,
            "bias_penalty_reference": 0.45,
        },
    },
    "literature_review": {
        "tier_quality_weight": {
            "tier1_official_anchor": 1.0,
            "tier2_official_survey": 0.9,
            "tier2_scientific_literature": 0.72,
            "tier3_structured_repository": 0.62,
            "tier4_proxy_dataset": 0.45,
            "default": 0.35,
        },
        "quality_score_weights": {
            "tier": 0.45,
            "domain": 0.25,
            "anchor_bonus": 0.1,
            "extraction_per_candidate": 0.03,
            "extraction_cap": 0.15,
            "parse_bonus": 0.08,
        },
        "promotion_thresholds": {
            "strong_numeric_confidence": 0.75,
            "supporting_confidence": 0.5,
            "main_predictive_numeric_count": 2,
            "supporting_document_count": 3,
        },
    },
    "phase2": {
        "skeleton_threshold": 0.05,
        "mi_prefilter": {
            "enabled": True,
            "mi_threshold": 0.005,
            "hist_bins": 12,
            "min_features_to_keep": 12,
            "target_tokens": [
                "testing",
                "diagnos",
                "viral",
                "suppression",
                "art",
                "cd4",
                "case_count",
                "linkage",
                "retention",
            ],
        },
        "pc_skeleton": {
            "alpha": 0.01,
            "max_conditioners": 1,
            "candidate_conditioners": 5,
            "corr_floor": 0.05,
        },
        "execution": {
            "compute_backend": "auto",
            "prefer_gpu": True,
            "interop_mode": "dlpack",
        },
        "lag_rules": {
            "blocked_pathway_pairs": [
                ["prevention_access", "suppression_outcomes"],
                ["testing_uptake", "suppression_outcomes"],
                ["linkage_to_care", "suppression_outcomes"],
                ["testing_uptake", "viral_suppression_rate"],
                ["linkage_to_care", "viral_suppression_rate"],
            ],
            "blocked_canonical_pairs": [
                ["prevention_access", "viral_suppression_rate"],
                ["testing_uptake", "art_uptake_rate"],
                ["testing_uptake", "viral_load"],
            ],
        },
        "notears": {
            "steps": 150,
            "optimizer_lr": 0.05,
            "lasso_penalty": 0.02,
            "ridge_penalty": 0.01,
            "acyclicity_penalty": 0.5,
            "optimizer_kind": "lbfgs",
            "outer_steps": 6,
            "lbfgs_max_iter": 24,
            "rho_init": 1.0,
            "rho_multiplier": 10.0,
            "h_tol": 1e-6,
            "weight_threshold": 1e-4,
        },
        "time_stratified_cv": {
            "enabled": True,
            "folds": 3,
            "holdout_months": 1,
            "min_train_months": 2,
            "optimizer_step_fraction": 0.35,
        },
        "collinearity": {
            "enabled": True,
            "high_corr_threshold": 0.92,
            "condition_number_warning": 200.0,
            "max_components": 8,
        },
        "blanket_edge_threshold": 0.03,
        "curation_status_thresholds": {
            "promoted_candidate": 0.72,
            "research_candidate": 0.45,
            "review": 0.28,
        },
        "stability_score_weights": {
            "source_diversity": 0.14,
            "geo_diversity": 0.10,
            "region_diversity": 0.08,
            "time_diversity": 0.08,
            "domain_diversity": 0.12,
            "pathway_diversity": 0.08,
            "tag_diversity": 0.10,
            "target_diversity": 0.10,
        },
        "stability_denominators": {
            "source_diversity": 3.0,
            "geo_diversity": 3.0,
            "region_diversity": 3.0,
            "time_diversity": 3.0,
            "domain_diversity": 3.0,
            "pathway_diversity": 3.0,
            "tag_diversity": 4.0,
            "target_diversity": 4.0,
        },
        "dag_score_weights": {"in_strength": 0.35, "out_strength": 0.35, "blanket_member": 0.30},
        "relevance_score_weights": {
            "support_count": 0.15,
            "numeric_support_ratio": 0.15,
            "direct_support_ratio": 0.14,
            "anchor_support_ratio": 0.10,
            "target_diversity": 0.14,
            "evidence_score": 0.12,
            "dag_score": 0.20,
        },
        "relevance_denominators": {"support_count": 6.0, "target_diversity": 3.0},
        "curation_mix": {"relevance_score": 0.45, "stability_score": 0.30, "dag_score": 0.25},
        "linkage_score_weights": {
            "support_count": 0.30,
            "relevance_score": 0.20,
            "stability_score": 0.15,
            "dag_score": 0.20,
            "numeric_support_ratio": 0.15,
        },
        "linkage_support_denominator": 4.0,
        "parameter_edge_weights": {
            "support_count": 0.15,
            "dag_score": 0.20,
            "stability_score": 0.20,
            "relevance_score": 0.20,
            "same_block_bonus": 0.25,
        },
        "factor_diagnostic_weights": {
            "stability_score": 0.26,
            "predictive_gain": 0.18,
            "subnational_anomaly_gain": 0.22,
            "region_contrast_score": 0.12,
            "source_dropout_robustness": 0.15,
            "missing_data_robustness": 0.10,
            "permutation_null_gap": 0.07,
        },
        "benchmark_artifacts": {
            "bootstrap_draws": 6,
            "bootstrap_steps": 32,
            "permutation_draws": 6,
            "permutation_steps": 24,
            "edge_threshold": 0.03,
            "top_edges": 25,
            "rng_seed": 31,
        },
        "shortlist_per_block": 6,
        "budgets": {"main": 8, "support": 12, "network_main": 3},
    },
    "phase15": {
        "similarity_weights": {
            "signature_cosine": 0.25,
            "corr_sim": 0.25,
            "semantic_sim": 0.15,
            "target_sim": 0.12,
            "source_sim": 0.08,
            "geo_sim": 0.08,
            "lane_sim": 0.07,
        },
        "similarity_quality": {
            "evidence_weight_mix": 0.5,
            "bias_penalty_mix": 0.5,
            "quality_floor": 0.2,
            "within_block_threshold": 0.34,
            "within_block_top_k": 4,
        },
        "factor_extraction": {
            "composite_weight_floor": 0.05,
            "svd_eps": 1e-6,
        },
        "network_graph": {
            "adjacency_top_k": 3,
            "same_region_bonus": 0.08,
            "positive_edge_threshold": 0.05,
            "shortest_path_floor": 0.05,
            "accessibility_floor": 1.0,
            "isolation_eps": 1e-6,
        },
        "stability": {
            "permutation_draws": 4,
            "missing_dropout_rate": 0.20,
            "source_dropout_network": 0.80,
            "source_dropout_non_seed": 0.75,
            "source_dropout_seed_only": 0.45,
            "score_weights": {
                "predictive_gain": 0.22,
                "subnational_gain": 0.22,
                "stability": 0.16,
                "sign_stability": 0.14,
                "missing_robustness": 0.10,
                "source_dropout_robustness": 0.08,
                "region_contrast": 0.08,
            },
            "main_thresholds": {
                "predictive_gain": 0.10,
                "subnational_gain": 0.12,
                "stability_score": 0.38,
                "sign_stability": 0.50,
                "null_gap": 0.01,
                "region_contrast": 0.05,
            },
            "support_thresholds": {
                "predictive_gain": 0.06,
                "subnational_gain": 0.08,
            },
        },
    },
        "phase3": {
        "testing_semantics": "viral_load_tested_stock",
        "testing_upper_target": "art_stock",
        "suppression_upper_target": "testing_coverage",
        "art_upper_target": "diagnosed_stock",
        "anchor_curve": {
            "official_decay_months": 18.0,
            "official_weight_floor": 0.15,
            "harp_decay_months": 14.0,
            "harp_weight_floor": 0.10,
            "linkage_growth_weight": 0.55,
            "linkage_hazard_weight": 0.45,
            "linkage_growth_floor": 0.02,
            "linkage_growth_ceiling": 0.35,
            "linkage_target_floor": 0.04,
            "linkage_target_ceiling": 0.28,
        },
        "subgroup_row_weight": {
            "measurement_base": 0.45,
            "measurement_scale": 0.25,
            "spatial_base": 0.35,
            "spatial_scale": 0.35,
            "tier_scale": 0.30,
            "geo_factor": {
                "province": 1.0,
                "city": 1.0,
                "region": 0.8,
                "national": 0.45,
                "unknown": 0.2,
            },
        },
        "subgroup_anchor_strength": {
            "national_distribution_scale": 18.0,
            "estimate_divisor": 80000.0,
            "coverage_scale": 6.0,
            "strength_floor": 2.0,
            "strength_ceiling": 20.0,
            "msm_share": 0.78,
            "tgw_share": 0.22,
            "remaining_population_discount": 0.40,
        },
        "network_signal_mix": {
            "urbanity": {"awareness": 0.40, "accessibility": 0.35, "inbound": 0.25, "isolation": -0.15},
            "stress": {"fragility": 0.55, "continuity": 0.45},
        },
        "feature_support": {
            "base": 0.35,
            "numeric_row_bonus": 0.20,
            "numeric_row_denominator": 4.0,
            "source_bank_bonus": 0.15,
            "source_bank_denominator": 4.0,
            "documented_suppression_biology_bonus": 0.10,
            "testing_coverage_behavior_bonus": 0.10,
        },
        "target_match": {
            "base_score": 0.25,
            "token_bonus": 0.35,
            "domain_bonus": 0.20,
            "pathway_bonus": 0.20,
            "top_k": 8,
        },
        "matched_support": {
            "weight_base": 0.50,
            "quality_scale": 0.30,
            "spatial_scale": 0.20,
        },
        "normalized_row_support": {
            "weight_base": 0.40,
            "quality_scale": 0.30,
            "spatial_scale": 0.30,
        },
        "torch_initialization": {
            "mobility_state_weights": [0.45, 0.35, 0.10, 0.00, 0.10],
            "service_state_weights": [0.05, 0.18, 0.36, 0.21, 0.20],
            "information_state_weights": [0.40, 0.34, 0.12, 0.04, 0.10],
            "duration_transition_start": -0.18,
            "duration_transition_end": 0.18,
            "duration_transition_scale": 0.50,
            "metapopulation_initial_logit": [-2.2, -2.35, -2.3],
            "cd4_low_coef_init": [0.16, 0.12, -0.08, 0.10, -0.05],
            "cd4_high_coef_init": [-0.12, -0.06, 0.14, -0.10, 0.05],
            "vl_test_share_floor": 0.10,
            "vl_test_share_ceiling": 0.95,
            "documented_given_test_floor": 0.50,
            "documented_given_test_ceiling": 0.995,
            "death_scale": 0.18,
            "diagnosed_margin": 0.02,
            "suppression_margin": 0.03,
            "testing_ceiling_scale": 0.95,
            "region_initial_penalty": 0.10,
            "province_initial_penalty": 0.15,
            "subgroup_transition_penalty": 0.08,
            "subgroup_prior_penalty": 0.50,
            "coupling_penalty": 0.25,
            "metapopulation_penalty": 0.08,
            "cd4_coef_penalty": 0.04,
            "cd4_prior_penalty": 0.50,
            "covariate_penalty": 0.10,
            "vl_test_smooth_penalty": 0.08,
            "documented_smooth_penalty": 0.06,
            "reporting_observation_weight_penalty": 0.04,
            "synthetic_pretraining_penalty": 0.03,
            "transition_scale_penalty": 0.04,
            "process_scale_penalty": 0.04,
            "observation_scale_penalty": 0.03,
            "archetype_noise_weight": 0.55,
        },
        "suppression_process": {
            "transition_weight": 1.00,
            "suppressed_among_art_weight": 0.95,
            "overall_weight": 0.70,
            "tested_among_art_weight": 0.55,
            "documented_given_test_weight": 0.65,
            "tested_process_smooth_weight": 0.20,
            "documented_process_smooth_weight": 0.25,
            "national_tested_gap_weight": 0.30,
        },
        "intervention_tensor": {
            "channels": [
                {"name": "diagnosis_intervention", "transition_indices": [0]},
                {"name": "linkage_intervention", "transition_indices": [1]},
                {"name": "suppression_intervention", "transition_indices": [2]},
                {"name": "retention_intervention", "transition_indices": [1, 3, 4]},
            ],
            "base_covariate_floor": 0.20,
        },
    },
    "node_graph": {
        "node_priors": {
            "constraint": 0.58,
            "advisory": 0.52,
            "decision_modifier": 0.50,
            "experimental": 0.35,
        },
        "posterior_update": {
            "truth_gain_weight": 1.2,
            "stability_weight": 0.9,
            "overlap_penalty_weight": 1.1,
            "drift_penalty_weight": 0.8,
            "z_clip": 2.0,
            "posterior_floor": 0.05,
            "posterior_ceiling": 0.95,
        },
        "signal_weights": {
            "mobility_network_mixing": {"accessibility": 0.55, "urbanity": 0.25, "stress": -0.70},
            "logistics_access": {"stress": -0.80, "accessibility_gap": -0.20},
            "service_delivery_infrastructure": {"art_mae": -0.55, "suppression_mae": -0.45},
            "stigma_behavior_information": {"awareness": 0.65, "stress": -0.45, "diagnosed_mae": -0.20},
            "population_structure_demography": {"kp_focus": 0.60, "urbanity": 0.25, "stress": -0.15},
            "policy_implementation": {"diagnosed_mae": -0.45, "art_mae": -0.30, "suppression_mae": -0.25},
            "benchmark_guardrails": {"diagnosed_mae": -0.45, "art_mae": -0.25, "suppression_mae": -0.30},
        },
        "consistency_weights": {"diagnosed_mae": 1.0, "suppression_mae": 0.5},
        "evidence_fallback": {
            "overlap_contrast_target": 0.4,
            "benchmark_pass_floor": 0.25,
            "benchmark_drift_target": 0.5,
        },
        "default_region_signal": {
            "accessibility": 0.5,
            "awareness": 0.0,
            "stress": 0.0,
            "urbanity": 0.5,
            "kp_focus": 0.5,
        },
        "signal_direction": {
            "support_floor": 0.05,
            "caution_ceiling": -0.05,
        },
        "confidence_mix": {
            "posterior_weight": 0.55,
            "consistency_weight": 0.45,
        },
        "caps": {
            "risk_bonus_max": 0.08,
            "risk_penalty_max": 0.12,
            "regional_support_max": 1.0,
            "regional_penalty_max": 1.0,
            "support_scale": 0.08,
            "penalty_scale": 0.12,
        },
        "veto": {"weight_threshold": 0.75, "signal_threshold": -0.80},
    },
}


HIV_POLICY_SETTINGS = {
    "phase4": {
        "intervention_channels": [
            "testing_expansion",
            "linkage_support",
            "art_retention",
            "viral_monitoring",
            "transport_support",
            "stigma_reduction",
            "workforce_deployment",
        ],
        "objectives": ["suppression_reward", "inequality_reward", "incidence_reward", "feasibility_reward"],
        "channel_effects": [
            [0.12, 0.02, 0.00, 0.00, -0.01],
            [0.00, 0.11, 0.03, 0.00, -0.02],
            [0.00, 0.02, 0.07, 0.06, -0.08],
            [0.00, 0.00, 0.08, 0.08, -0.02],
            [0.04, 0.05, 0.01, 0.00, -0.05],
            [0.05, 0.04, 0.00, 0.00, -0.04],
            [0.05, 0.07, 0.05, 0.03, -0.04],
        ],
        "activation_thresholds": [0.05, 0.06, 0.07, 0.04, 0.06, 0.05, 0.08],
        "saturation": [4.0, 3.8, 3.4, 4.2, 3.1, 3.3, 2.8],
        "rollout_decay": 0.20,
        "feasibility_variance_weight": 0.25,
        "scalar_objective_weights": [0.42, 0.18, 0.30, 0.10],
        "counterfactual_score_ceiling": 1.0,
        "counterfactual": {
            "dirichlet_base_alpha": 1.2,
            "dirichlet_score_scale": 6.0,
            "alpha_floor": 0.30,
            "blanket_bonus": 0.05,
            "blanket_bonus_scale": 0.02,
            "testing_domain_bonus": 0.01,
            "art_biology_bonus": 0.01,
            "target_bonus_scale": 0.05,
            "suppression_gap_target": 0.95,
            "channel_targets": {
                "testing_expansion": ["testing_uptake", "prevention_access"],
                "linkage_support": ["linkage_to_care", "testing_uptake"],
                "art_retention": ["retention_adherence", "suppression_outcomes"],
                "viral_monitoring": ["suppression_outcomes", "biological_progression"],
                "transport_support": ["health_system_reach", "mobility_network_mixing"],
                "stigma_reduction": ["prevention_access", "testing_uptake", "linkage_to_care"],
                "workforce_deployment": ["health_system_reach", "retention_adherence", "suppression_outcomes"],
            },
            "base_scores": {
                "testing_expansion": {"U": 0.60, "V_gap": 0.25},
                "linkage_support": {"D": 0.55, "U": 0.20, "V_gap": 0.10},
                "art_retention": {"A": 0.55, "L": 0.45},
                "viral_monitoring": {"A": 0.45, "V_gap": 0.40},
                "transport_support": {"U": 0.35, "L": 0.35, "D": 0.10},
                "stigma_reduction": {"U": 0.40, "D": 0.30, "V_gap": 0.15},
                "workforce_deployment": {"U": 0.25, "D": 0.30, "A": 0.25, "L": 0.10},
            },
        },
        "node_graph": {
            "policy_score_bonus_scale": 0.50,
            "policy_score_penalty_scale": 0.65,
            "decision_support_multiplier": 0.06,
            "decision_penalty_multiplier": 0.10,
            "decision_multiplier_floor": 0.70,
            "frontier_support_multiplier": 0.03,
            "frontier_penalty_multiplier": 0.05,
            "frontier_veto_penalty": 0.01,
            "frontier_multiplier_floor": 0.70,
            "channel_map": {
                "mobility_network_mixing": {"transport_support": 1.0, "linkage_support": 0.55, "testing_expansion": 0.15},
                "logistics_access": {"transport_support": 1.0, "workforce_deployment": 0.60, "viral_monitoring": 0.20},
                "service_delivery_infrastructure": {"art_retention": 0.85, "viral_monitoring": 1.0, "workforce_deployment": 0.70},
                "stigma_behavior_information": {"testing_expansion": 0.90, "stigma_reduction": 1.0, "linkage_support": 0.40},
                "population_structure_demography": {"testing_expansion": 0.50, "linkage_support": 0.45, "stigma_reduction": 0.20},
                "policy_implementation": {channel: 0.45 for channel in ["testing_expansion", "linkage_support", "art_retention", "viral_monitoring", "transport_support", "stigma_reduction", "workforce_deployment"]},
                "benchmark_guardrails": {channel: 0.25 for channel in ["testing_expansion", "linkage_support", "art_retention", "viral_monitoring", "transport_support", "stigma_reduction", "workforce_deployment"]},
            },
        },
        "stochastic_control": {
            "trajectory_count": 12,
            "transition_concentration": 48.0,
            "rng_seed": 23,
            "transition_floor": 0.001,
            "transition_ceiling": 0.95,
            "beta_floor": 0.001,
        },
        "policy_search": {
            "rollouts": 192,
            "horizon": 6,
            "rng_seed": 23,
        },
        "analysis": {
            "sensitivity_shift": 0.04,
            "top_counterfactual_channels": 2,
        },
        "mpc": {
            "control_horizon": 2,
            "replan_step": 3,
        },
        "regional_allocation": {
            "zero_budget_eps": 1e-8,
        },
        "regional_priority_weights": {
            "testing_expansion": {"U": 0.58, "diagnosed_mae": 0.15, "under_reporting": 0.18, "urban": 0.09},
            "linkage_support": {"D": 0.52, "art_mae": 0.20, "migrant": 0.18, "fragile": 0.10},
            "art_retention": {"A_plus_L": 0.45, "art_mae": 0.25, "fragile": 0.20, "remote": 0.10},
            "viral_monitoring": {"A": 0.48, "suppression_mae": 0.22, "fragile": 0.20, "under_reporting": 0.10},
            "transport_support": {"L": 0.42, "remote": 0.25, "migrant": 0.20, "art_mae": 0.13},
            "stigma_reduction": {"U": 0.45, "D": 0.22, "under_reporting": 0.15, "urban": 0.18},
            "workforce_deployment": {"D": 0.26, "A": 0.22, "art_mae": 0.22, "fragile": 0.18, "remote": 0.12},
        },
        "base_transition_map": {
            "U_to_D": {"intercept": 0.08, "state_index": 0, "slope": 0.35, "floor": 0.01, "ceiling": 0.80},
            "D_to_A": {"intercept": 0.05, "state_index": 1, "slope": 0.40, "floor": 0.01, "ceiling": 0.80},
            "A_to_V": {"intercept": 0.04, "state_index": 2, "slope": 0.42, "floor": 0.01, "ceiling": 0.80},
            "A_to_L": {"intercept": 0.02, "state_index": 4, "slope": 0.30, "floor": 0.005, "ceiling": 0.60},
            "L_to_A": {"intercept": 0.03, "state_index": 4, "slope": 0.28, "floor": 0.005, "ceiling": 0.60},
        },
    },
}


HIV_GOLD_STANDARD_PROFILES = {
    "phase0": {
        "mode": "authoritative_external",
        "truth_claim_level": "process_quality",
        "benchmark_policy": "authoritative_standard_plus_process_quality",
        "description": "Evidence retrieval and measurement alignment must be judged on provenance, completeness, consistency, and uncertainty propagation.",
        "judging_principles": [
            "PRISMA-style evidence traceability",
            "WHO DQA completeness, timeliness, and internal consistency",
            "explicit provenance for every extracted numeric row",
            "measurement uncertainty propagated rather than hidden",
        ],
        "required_claims": [
            "Phase 0 should never claim semantic retrieval is itself a gold standard.",
            "OCR and vector search are implementation choices, not external standards.",
        ],
        "standards": [
            {"id": "prisma_2020", "title": "PRISMA 2020", "category": "systematic_evidence", "url": "https://www.prisma-statement.org/citing-prisma-2020"},
            {"id": "who_dqr", "title": "WHO Data Quality Review modules", "category": "data_quality", "url": "https://www.who.int/data/data-collection-tools/health-service-data/toolkit-for-routine-health-information-system-data/modules"},
            {"id": "who_hiv_si_2020", "title": "WHO Consolidated HIV Strategic Information Guidelines (2020)", "category": "hiv_monitoring", "url": "https://www.who.int/publications-detail-redirect/9789240000735"},
            {"id": "who_hiv_si_2022", "title": "WHO Person-Centred HIV Strategic Information Guidelines (2022)", "category": "hiv_monitoring", "url": "https://www.who.int/publications-detail-redirect/9789240055315"},
            {"id": "prov_o", "title": "W3C PROV-O", "category": "provenance", "url": "https://www.w3.org/TR/prov-o/"},
            {"id": "gum_2008", "title": "JCGM 100:2008 Guide to the Expression of Uncertainty in Measurement", "category": "measurement_uncertainty", "url": "https://www.bipm.org/doi/10.59161/JCGM100-2008E"},
        ],
    },
    "phase1": {
        "mode": "authoritative_external",
        "truth_claim_level": "measurement_quality",
        "benchmark_policy": "authoritative_standard_plus_method_choice",
        "description": "Normalization should preserve denominator semantics, uncertainty, and RHIS consistency; robust scaling is a justified method choice rather than an HIV program standard.",
        "judging_principles": [
            "measurement uncertainty preserved after normalization",
            "no denominator or unit ambiguity",
            "robust scaling documented as a statistical method choice",
            "no silent distortion of low-volume provinces",
        ],
        "required_claims": [
            "Median/IQR scaling should be described as robust statistics, not an official HIV program mandate.",
        ],
        "standards": [
            {"id": "gum_2008", "title": "JCGM 100:2008 Guide to the Expression of Uncertainty in Measurement", "category": "measurement_uncertainty", "url": "https://www.bipm.org/doi/10.59161/JCGM100-2008E"},
            {"id": "who_dqr", "title": "WHO Data Quality Review modules", "category": "data_quality", "url": "https://www.who.int/data/data-collection-tools/health-service-data/toolkit-for-routine-health-information-system-data/modules"},
            {"id": "nist_robust", "title": "NIST guidance on robust location and scale", "category": "robust_statistics", "url": "https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/iqr.htm"},
        ],
    },
    "phase15": {
        "mode": "benchmark_family",
        "truth_claim_level": "mesoscopic_benchmark",
        "benchmark_policy": "stability_and_null_ladder",
        "description": "Mesoscopic factor construction has no single external gold truth; it should be judged by stability, subnational contrast, permutation-null gaps, and source-dropout robustness.",
        "judging_principles": [
            "factor stability across environments",
            "permutation-null separation",
            "source-dropout robustness",
            "subnational contrast preserved",
        ],
        "required_claims": [
            "Phase 1.5 should be described as a benchmark-family layer, not a gold-truth layer.",
        ],
        "standards": [
            {"id": "phase15_internal_benchmark", "title": "Mesoscopic factor stability and null ladder", "category": "benchmark_family", "url": "https://github.com/gauravshajepal-hash/ModelHIV-PH"},
            {"id": "gum_2008", "title": "JCGM 100:2008 Guide to the Expression of Uncertainty in Measurement", "category": "measurement_uncertainty", "url": "https://www.bipm.org/doi/10.59161/JCGM100-2008E"},
        ],
    },
    "phase2": {
        "mode": "benchmark_family",
        "truth_claim_level": "benchmark_only",
        "benchmark_policy": "known_graph_and_stability_ladder",
        "description": "Causal discovery should be benchmarked against admissibility, acyclicity, known graph families, and stability rather than claimed as an external Philippines truth graph.",
        "judging_principles": [
            "exact acyclicity",
            "tier and lag mask compliance",
            "known graph recovery benchmarks",
            "bootstrap and permutation stability",
        ],
        "required_claims": [
            "Phase 2 must never be described as having a single external truth set for the Philippines determinant DAG.",
        ],
        "standards": [
            {"id": "sachs_2005", "title": "Sachs et al. causal protein-signaling benchmark", "category": "known_graph_benchmark", "url": "https://pubmed.ncbi.nlm.nih.gov/15845847/"},
            {"id": "pcmci_family", "title": "Runge/PCMCI time-series causal discovery benchmark family", "category": "time_series_benchmark", "url": "https://arxiv.org/abs/2003.03685"},
            {"id": "tripod_ai", "title": "TRIPOD+AI", "category": "reporting", "url": "https://www.bmj.com/content/388/bmj-2024-082124"},
            {"id": "probast_ai", "title": "PROBAST+AI", "category": "bias_assessment", "url": "https://www.bmj.com/content/388/bmj-2024-082505"},
        ],
    },
    "phase3": {
        "mode": "hybrid_authoritative",
        "truth_claim_level": "strongest_truth_claim",
        "benchmark_policy": "official_indicator_and_program_anchor_ladder",
        "description": "The latent HIV core should be judged against official denominator definitions, observed program anchors, frozen backtests, and incumbent epidemic-estimation comparators.",
        "judging_principles": [
            "exact denominator semantics for 95-95-95 views",
            "WHO/UNAIDS suppression semantics",
            "historical frozen backtests against HARP",
            "comparison against naive carry-forward and incumbent estimators where available",
        ],
        "required_claims": [
            "Phase 3 carries the strongest external truth claims in the repo.",
            "Comparator absence should be reported explicitly, not hidden.",
        ],
        "standards": [
            {"id": "unaids_95_2024", "title": "UNAIDS 95-95-95 methods annex", "category": "indicator_definitions", "url": "https://crossroads.unaids.org/wp-content/uploads/2024/07/GAU-2024-Annex-2-En.pdf"},
            {"id": "who_hiv_si_2020", "title": "WHO Consolidated HIV Strategic Information Guidelines (2020)", "category": "hiv_monitoring", "url": "https://www.who.int/publications-detail-redirect/9789240000735"},
            {"id": "who_hiv_si_2022", "title": "WHO Person-Centred HIV Strategic Information Guidelines (2022)", "category": "hiv_monitoring", "url": "https://www.who.int/publications-detail-redirect/9789240055315"},
            {"id": "who_viral_suppression_2023", "title": "WHO Viral Suppression Policy Brief (2023)", "category": "suppression_semantics", "url": "https://www.who.int/publications/i/item/9789240055179"},
            {"id": "spectrum_manual", "title": "Spectrum manual", "category": "incumbent_comparator", "url": "https://avenirhealth.org/Download/Spectrum/Manuals/SpectrumManualS.pdf"},
            {"id": "pepfar_mer", "title": "PEPFAR MER indicator guides", "category": "program_indicator_comparator", "url": "https://help.datim.org/hc/en-us/articles/360000084446-MER-Indicator-Reference-Guides"},
        ],
    },
    "phase4": {
        "mode": "benchmark_family",
        "truth_claim_level": "decision_benchmark",
        "benchmark_policy": "comparator_policy_and_sensitivity_ladder",
        "description": "Decision and control outputs should be judged by decision-modeling good practice, stochastic stability, and comparator policy performance rather than a single truth set.",
        "judging_principles": [
            "uncertainty preserved through decision scoring",
            "policy comparisons externally auditable",
            "sensitivity and stability analysis present",
            "allocation must beat naive and current-policy comparators",
        ],
        "required_claims": [
            "Phase 4 should be described as a benchmark-family decision layer, not an external truth layer.",
        ],
        "related_layers": ["node_graph"],
        "standards": [
            {"id": "ispor_smdm", "title": "ISPOR-SMDM modeling good research practices", "category": "decision_modeling", "url": "https://www.sciencedirect.com/science/article/pii/S1098301512016567"},
            {"id": "ahrq_modeling", "title": "AHRQ guidance for modeling and simulation studies", "category": "decision_modeling", "url": "https://effectivehealthcare.ahrq.gov/products/decision-modeling-simulation/research-protocol"},
            {"id": "cheers_2022", "title": "CHEERS 2022", "category": "reporting", "url": "https://www.bmj.com/content/376/bmj-2021-067975"},
        ],
    },
    "node_graph": {
        "mode": "benchmark_family",
        "truth_claim_level": "runtime_assurance",
        "benchmark_policy": "provenance_and_invariant_ladder",
        "description": "The node graph is a runtime assurance layer that must preserve provenance and never rewrite the epidemic core.",
        "judging_principles": [
            "strict provenance for every node signal",
            "reproducible evidence scoring",
            "no structural forecast mutation when disabled",
            "decision-layer effects only",
        ],
        "required_claims": [
            "Node graph outputs should be described as runtime constraints, not disease dynamics.",
        ],
        "standards": [
            {"id": "prov_o", "title": "W3C PROV-O", "category": "provenance", "url": "https://www.w3.org/TR/prov-o/"},
            {"id": "ispor_smdm", "title": "ISPOR-SMDM modeling good research practices", "category": "decision_modeling", "url": "https://www.sciencedirect.com/science/article/pii/S1098301512016567"},
        ],
    },
}


HIV_PLUGIN = register_disease_plugin(
    DiseasePlugin(
        plugin_id="hiv",
        display_name="Human Immunodeficiency Virus",
        state_catalog=["U", "D", "A", "V", "L"],
        observation_families=["direct_observed", "bounded_observed", "proxy_observed", "prior_only"],
        intervention_channels=[
            "testing_expansion",
            "linkage_support",
            "art_retention",
            "viral_monitoring",
            "transport_support",
            "stigma_reduction",
            "workforce_deployment",
        ],
        query_banks=HIV_QUERY_BANKS,
        determinant_silos=HIV_DETERMINANT_SILOS,
        structured_source_adapters=get_structured_source_adapters("hiv"),
        node_graph_defaults=HIV_NODE_GRAPH_DEFAULTS,
        prior_hyperparameters=HIV_PRIOR_HYPERPARAMETERS,
        numerical_stabilizers=HIV_NUMERICAL_STABILIZERS,
        constraint_settings=HIV_CONSTRAINT_SETTINGS,
        policy_settings=HIV_POLICY_SETTINGS,
        reference_data=HIV_REFERENCE_DATA,
        gold_standard_profiles=HIV_GOLD_STANDARD_PROFILES,
        notes=[
            "First plugin with rescue-core state topology U,D,A,V,L.",
            "Determinant silos are literature-first and source-adapter-aware rather than direct latent-state replacements.",
            "Fixed numeric settings are classified as prior hyperparameters, numerical stabilizers, constraint settings, or policy settings.",
        ],
    )
)
